---

#The purpose of this task is to install common applications across all machines. 

  - name: Install basic features
    yum: name={{ item }} state=present
    with_items:
      - nano
      - wget
      - libselinux-python
