---

#The purpose of this task is to install common applications across all machines. 

  - name: Install Openssl
    yum: name=openssl-devel state=present

  - name: Make directory for files
    file: path=/etc/ssl/xip.io state=directory mode=0755 

  - name: Create certificate
    command: openssl req -new -nodes -x509 -subj "/C=US/ST=Florida/L=Orlando/O=IT/CN=seeddms.project" -days 365 -keyout /etc/ssl/xip.io/project.key 1024 -out /etc/ssl/xip.io/project.crt

  - name: create ".pem" file for HAProxy
    command: cat /etc/ssl/xip.io/project.crt /etc/ssl/xip.io/project.key \ | sudo tee /etc/ssl/xip.io/project.pem
