---

#The purpose of this task is to install common applications across all machines and update them to their latest versions. 

  - name: Install basic features
    yum: name={{ item }} state=present
    with_items:
      - epel-release
      - nano
      - wget
      - libselinux-python
      
  - name: update CentOS
    yum: name=* state=latest update_cache=yes
